name: JMeter Performance Test (Docker Stable)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run JMeter with Docker
      run: |
        mkdir -p results

        docker run --rm \
          -v ${{ github.workspace }}:/test \
          -w /test \
          justb4/jmeter:latest \
          -n \
          -t guru99v2.jmx \
          -l results/results.jtl \
          -Jjmeter.save.saveservice.script=false

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: results
